{
 "title": "Covid-19",
 "time": { "from": "now-2d/d", "to": "now-2d/d" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country/Region",
    "query": "select distinct(country) from covid_data"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 0 },
   "content": "<h4 style=\"text-align:right;text-transform:uppercase;v-align:middle;font-size:25px;margin-right:150px;\" markdown=\"1\"><b>covid-19 Dashboard monitoring</font></h4>",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT\n  datex AS \"time\",\n  cast(confirmed as int)\nFROM covid_data\nWHERE\n  $__timeFilter(datex) AND\n  country like $country\nORDER BY datex"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  datex AS \"time\",\n  sum(cast(confirmed as int))\nFROM covid_data\nWHERE\n  $__timeFilter(datex) AND\n  country like $country\ngroup by 1\nORDER BY datex desc\nlimit 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\nsum(cast(recovered as int)) as value,\ndatex as time\nfrom covid_data\nwhere $__timeFilter(datex) and\ncountry like $country\ngroup by 2\norder by 2 desc\nlimit 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select\nsum(cast(recovered as int))/sum(cast(confirmed as int))*100 as value,\ndatex as time\nfrom covid_data\nwhere $__timeFilter(datex) and\ncountry like $country\ngroup by 2 \norder by 2 desc\nlimit 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\nsum(cast(deaths as int)) as value,\ndatex as time\nfrom covid_data\nwhere $__timeFilter(datex)and\ncountry like $country\ngroup by 2\norder by 2 desc\nlimit 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\nsum(cast(deaths as int))/sum(cast(confirmed as int))*100 as value,\ndatex as time\nfrom covid_data\nwhere $__timeFilter(datex) and\ncountry like $country\ngroup by 2\norder by 2 desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Daily Trend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\ndatex as time,\n'Confirmed' as metric,\nsum(cast(confirmed as int)) as value\nfrom covid_data\nwhere\ncountry like $country\ngroup by 1\norder by 1\n"
    },
    {
     "rawSql": "select\ndatex as time,\n'Recovered' as metric,\nsum(cast(recovered as int)) as value\nfrom covid_data\nwhere\ncountry like $country\ngroup by 1\norder by 1"
    },
    {
     "rawSql": "select\ndatex as time,\n'Deaths' as metric,\nsum(cast(deaths as int)) as value\nfrom covid_data\nwhere\ncountry like $country\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Top 5 Region by Recovery Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "select country, cast(recovered as int)/cast(confirmed as int)*100 as RecoveryRate, confirmed as ConfirmedCase\nfrom covid_data\nwhere $__timeFilter(datex)\norder by datex desc, RecoveryRate desc\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Top 5 Region by Mortality Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "select country, cast(deaths as int)/cast(confirmed as int)*100 as MortalityRate, confirmed as ConfirmedCase\nfrom covid_data\nwhere $__timeFilter(datex)\norder by datex desc, MortalityRate desc\nlimit 5\n"
    }
   ]
  }
 ]
}